version: 2.1

executors:
  base-executor:
    docker:
      - image: cimg/base:2023.05
        # auth:
        #   username: $GITHUB_USERNAME
        #   password: $GITHUB_PAT  # context / project UI env-var reference
    # working_directory: /tmp

jobs:
  build:
    # resource_class: small # specify a resource class
    executor: base-executor
    steps:
      - checkout  
      - setup_remote_docker:
          docker_layer_caching: true
          
      - run:
          name: Build and push Docker image
          command: |
            export DOCKER_BUILDKIT=1
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t ghcr.io/kcirtapfromspace/cloudfoundry_circleci:$TAG .
            echo $GITHUB_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker push ghcr.io/kcirtapfromspace/cloudfoundry_circleci:$TAG
  deploy:
    executor: base-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Cloud Foundry
          command: |
            # ...first add the Cloud Foundry Foundation public key and package repository to your system
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            # ...then, update your local package index, then finally install the cf CLI
            sudo apt-get update
            sudo apt-get install cf8-cli

workflows:
  my-workflow:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
