version: 2
jobs:
  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Cloud Foundry
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=v7&source=github'
            sudo dpkg -i cf-cli_amd64.deb
  build:
    # resource_class: small # specify a resource class
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: cimg/base:2023.05
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout  
      - setup_remote_docker:
          docker_layer_caching: true
          
      - run:
          name: Build and push Docker image
          command: |
            export DOCKER_BUILDKIT=1
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t ghcr.io/kcirtapfromspace/cloudfoundry_circleci:$TAG .
            echo $GITHUB_PAT | docker login ghcr.io -u GITHUB_USERNAME --password-stdin
            docker push ghcr.io/kcirtapfromspace/cloudfoundry_circleci:$TAG
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
